global.exception.already.exists=Bu {name} zaten var ({value})
global.exception.not.found=Bu {name} ile ilgili bir kayıt bulunamadı ({value})
global.exception.internal.error=Beklenmeyen bir hata oluştu. Bunu ekibimize bildirdik.
global.exception.unsupported.operation=Bu işlem şuanda desteklenmiyor.
global.exception.invalid.param=Geçersiz bir değer gönderildi. Detayları kontrol ediniz.
global.exception.invalid.payload=Geçersiz bir istek gönderildi. Gönderilen verileri kontrol ediniz.